### ISSUE TITLE
Prometheus metrics endpoint

### ISSUE THREAD

**Issue by aliok** [sclorg/nodejs-ex#161]
Hi,

In our group (https://aerogear.org/ and http://feedhenry.org/), we're currently implementing Prometheus metrics endpoints for our applications that run on OpenShift.

We're using Prometheus' auto-discovery method to find out the services to monitor. When the service has a special annotation on it, it will be marked as metrics target by Prometheus and then the metrics endpoint will be requested regularly.

Do you think this kind of metrics would be a nice addition to this sample application?

I modified this sample application to add metrics to it: https://github.com/aliok/node-app-with-prometheus-metrics
If you like, I can clean it up and send a PR. 
What to provide as metrics is something we can discuss. 
Currently, there is only some random metrics value is provided in that app.

* If you don't like this idea and want to keep this example as simple as it is, we can perhaps create a fork of this application in OpenShift Github org with metrics.
* Or, we can move my sample app to OpenShift Github org after some clean up: https://github.com/aliok/node-app-with-prometheus-metrics
* If you didn't like any of those, I can just write a blog post about it :)

**Comment by aliok** [comment]
BTW, this is some documentation we prepared:
- https://github.com/aerogear/service-docs/blob/master/making-mobile-services-discoverable-by-metrics.adoc
- https://www.youtube.com/edit?o=U&video_id=AC_Xet-B1fY

**Comment by bparees** [comment]
I think I would like to keep this sample app pretty basic, so a separate repo that serves as a prometheus metrics example application would be preferred.  I don't have an opinion on whether that should be your existing sample or an enhancement of this one.

**Comment by sghosh151** [comment]
@aliok  Can you update the youtube link? "edit" link...
Agree - have it be separate is better, but have a link to it in the reademe.md would be great.

**Comment by aliok** [comment]
@bparees then let's close this ticket. I think in order to keep things simple, it makes sense to have a separate application. This way, this example application would feature basic things and that application would feature nothing but Prometheus integration.

I will do this sometime and let you know.
