### ISSUE TITLE
Adding new express routes

### ISSUE THREAD

**Issue by pazzipanda** [sclorg/nodejs-ex#164]
So I tried adding another route to the express router. It worked just fine on localhost, but when I push the code to openshift, a get to the new route returns with the "Cannot GET /...". I simpled it down to just copy-paste the existing app route /pagecount and just changed the name to app.get('page*' [..]) so that I'm sure nothing else interferes with the route. Still not getting me any results when GETting the route with postman or visiting it directly on the browser.

I'm pretty  new to openshift, have I missed something? Do I maybe need to create the routes at some other place than the server.js too? Help's appretiated!

##### Steps To Reproduce
1. Install the repository
2. copy the app.get('/pagecount' [...]) and change it to app.get('/page'[..]) ((or basicly anything)

##### Current Result
Throws  Cannot GET /page 

##### Expected Result
Same as GET /pagecount

##### Link
Here's the link to my server.js

https://github.com/pazzipanda/leagueStatus/blob/master/server.js

**Comment by bparees** [comment]
Are you sure you build your new code?  If you oc rsh into your running nodejs pod and look at the server.js, does it contain your changes?

**Comment by pazzipanda** [comment]
Okay, I feel very stupid now. I had this project here as my Source Repo, not my own. Thank you very much for pointing me in the right direction

**Comment by bparees** [comment]
glad you got it working :)
