### ISSUE TITLE
nodejs couldn't connect to mongodb in tutorial 

### ISSUE THREAD

**Issue by woodenleaves** [sclorg/nodejs-ex#192]
Today I follow the instructions exactly in https://docs.openshift.com/online/getting_started/beyond_the_basics.html but find that the mongodb is not connected to nodejs app. The Page view count shows No database configured.

Also could you provide more information about how mongdb is connected to nodejs in openshift? There is not much such information online.

**Comment by bparees** [comment]
> Also could you provide more information about how mongdb is connected to nodejs in openshift? There is not much such information online.

It's just nodejs application logic: 
https://github.com/sclorg/nodejs-ex/blob/master/server.js#L11-L57

Note that the primary way it connects is via the MONGO_URL env var.

i suggest you double check the steps in https://docs.openshift.com/online/getting_started/beyond_the_basics.html#btb-setting-environment-variables

to ensure you setup all the env vars properly, as well as confirming that your mongodb service exists and the mongodb pod is running successfully.

**Comment by woodenleaves** [comment]
Thanks a lot! I will read it more carefully and try it again after that.
