### ISSUE TITLE
Nodejs-ex app failed to start on Openshift

### ISSUE THREAD

**Issue by bgeorges** [sclorg/nodejs-ex#202]
The nodejs-ex app runs fine locally (bare-metal) on my machine, however when running it via 
`npm install && npm run openshift`  on Openshift (both OKD and OSO Pro) fails. See attached logs 

- [booster-1.log](https://github.com/sclorg/nodejs-ex/files/2351624/booster-1.log) => OSO Pro instance.
- [2018-09-05T06_40_31_854Z-debug.log](https://github.com/sclorg/nodejs-ex/files/2351625/2018-09-05T06_40_31_854Z-debug.log)  => local instance `oc cluster up`

**Comment by bparees** [comment]
please provide full recreate steps.  not clear what "running it via npm install && npm run openshift" means.

Also unless it's broken when running "oc new-app https://github.com/openshift/nodejs-ex" I am going to propose it's your workflow and not the app that is broken.

**Comment by bgeorges** [comment]
Ben,
I realised that I was following another example and their flow, and accidentally raised the issue in the wrong project. I'll move the issue to the appropriate place and close this one.
