### ISSUE TITLE
openshift pipeline issue

### ISSUE THREAD

**Issue by idavollen** [sclorg/nodejs-ex#223]
I am currently learning Openshift Pipeline and have one question concerning your code. With Readme.md under the folder _pipeline_
```
# now create the pipeline build controller from the openshift/pipeline
# subdirectory
oc new-app https://github.com/sclorg/nodejs-ex \
  --context-dir=openshift/pipeline --name nodejs-ex-pipeline
```
According to the Openshift Pipeline documentation, one **jenkinsPipelineStrategy** strategy has to be specified in a certain _BuildConfig_ in order to use pipeline, but I can find it within your project.

Can someone shed the light on how jenkinsPipelineStrategy is enabled with your project?

**Comment by bparees** [comment]
oc new-app will detect that presence of the Jenkinsfile and create a BuildConfig that uses the pipeline strategy.

if you run the oc new-app command with `-o yaml` you can see what it is going to create.
