### ISSUE TITLE
Move templates to another database

### ISSUE THREAD

**Issue by yselkowitz** [sclorg/nodejs-ex#242]
Red Hat has stopped packaging new versions of MongoDB due to its being switched to the SSPL, and no version was ever packaged for RHEL8.  The OpenShift templates use mongodb exclusively, meaning that at some point they will have to be dropped, leaving no templates left for nodejs.  New templates which use any of the supported databases (MariaDB, MySQL, Redis, and PostgreSQL) are needed instead.

**Comment by phracek** [comment]
@yselkowitz In ` openshift/templates` directory are two file `nodejs-mongodb.json` and `nodejs-mongodb-persistent.json`. Do you have any working examples with mariadb or MySQL?

**Comment by yselkowitz** [comment]
This is a stale issue, we since were given postgresql based templates from https://github.com/nodeshift-starters/nodejs-rest-http-crud/tree/master/.openshift instead of these.

**Comment by phracek** [comment]
@yselkowitz @hhorak Does it mean, that this example repo can not be used for RHEL8? I think we should update templates so that nodejs-ex can be used by the others, otherwise, this example repo is valid only for RHEL-7. What do you think?

**Comment by yselkowitz** [comment]
Yes, in fact we deprecated (hid) these templates in 4.6 (which was the first to include RHEL8-based SCL imagestreams and templates) for this very reason.  Since we're using the aforementioned CRUD as a postgresql example, if you want to port this to mysql or (even better imo) mariadb, we could have both.

However, since the image-ecosystem E2E still relies on the existing nodejs-mongodb-example template, we'll need to have a branch on which the existing code still lives in order to not break testing.  So, for instance, if you create a mongodb branch off of master today, then we need to define `SOURCE_REPOSITORY_REF` to match in the template, and adjust the URL of this template in openshift/library.  That would allow you to safely port the master branch to mysql/mariadb.

Let me know if I can be of assistance on the openshift/library side.

**Comment by phracek** [comment]
I will test this in s2i-nodejs-container directly. Please be patient for the PR that will be filed soon.

**Comment by lholmquist** [comment]
since we've already moved our crud [example to postgres](https://github.com/nodeshift-starters/nodejs-rest-http-crud/tree/main), i wonder if we can just deprecate this repo and use that instead?

**Comment by phracek** [comment]
We will migrate this repo from `mongodb` to `postgresql`. As was discussed with our team. CC @pkubatrh @hhorak @zmiklank 

Or maybe help from you. Can you please migrate it? @yselkowitz @lholmquist

**Comment by phracek** [comment]
PR for migration from MongoDB -> PostgreSQL is here: https://github.com/sclorg/nodejs-ex/pull/277

**Comment by phracek** [comment]
This can be closed. It is fixed in favor of https://github.com/sclorg/nodejs-ex/pull/277
